### ISSUE TITLE
Stream and multi rtsp in one page

### ISSUE THREAD

**Issue by duy1851999** [mpromonet/rtsp2web#1]
I display multiple rtsp cameras on the web with the tags convert that you give, it works fine, but when I want to show 3 camera videos to the browser without the switch tags, the video so lags. Is there any way to help display multiple videos in one page more smoothly?

**Comment by mpromonet** [comment]
Hi @duy1851999 

I am not sure to understand what you call "tag convert" and "switch tag", however there is problem to solve with multiple video, if you try the page /all.html or /worker.html there is lag, and lack of browser responsivness. There is several tracks like using webgpu for rendering and drop old frame, maybe some dejittering....

Best Regards,
Michel.

**Comment by duy1851999** [comment]
Is this repo rtsp2web using webRTC or websocket?

**Comment by mpromonet** [comment]
Hi @duy1851999 

This is simple websocket that forward encoded packet.

Best Regards,
Michel.
