### ISSUE TITLE
How run rtsp2web server using SSL/TLS

### ISSUE THREAD

**Issue by antonioaguilar** [mpromonet/rtsp2web#3]
Hi there,

Is the ```--sslkeycert``` flag implemented?

I tried to run the demo of the rtsp server using the ```--sslkeycert``` flag but didn't seem to have any effect. I used the following command:

```
./rtsp2ws -P 8443 -p ./www -C ./config.json -c ./keycert.pem
```

> Note: this is using the same certificate on your repo `keycert.pem`

I got a chrome browser error: *ERR_SSL_PROTOCOL_ERROR* when trying to load the `https://localhost:8443`. 

Then when I ran the demo on port 8080 I was not able to run the demo due to the `VideoDecoder` object being `undefined`. Because it's not available on non-secure contexts. 
 
I don't want to run the chrome browser on insecure mode by passing the `#unsafely-treat-insecure-origin-as-secure` flag. 

Any suggestions?

**Comment by mpromonet** [comment]
Hi,

You need to configure listening port using ssl, sée civetweb doc. This should work using `-P 8443s`.

Best Regards 
Michel

**Comment by antonioaguilar** [comment]
@mpromonet I was not familiar with the civetweb server, using `-P 8443s` worked. Thanks.
