### ISSUE TITLE
rtsp2ws.exe -c "keycert.pem" still served HTTP server, not HTTPS ?

### ISSUE THREAD

**Issue by strong0716** [mpromonet/rtsp2web#5]
This project is amazing!

I have successfully sent the H.265 RTSP stream to Chrome for preview. Thank you very much!

However, when I tested it on another computer, I encountered an issue. When I opened the website from the other computer, the browser required the video and audio decoder to use SSL (wss).

So, I used the following command in a Windows batch file:

`rtsp2ws.exe -P 10060 -N 2 -c "keycert.pem" -C config2.json`

But I was unable to connect to the HTTPS site; it still served HTTP. I also tested wss://localhost:10060/test9001 (test9001 is defined in my config2.json file), but it responded with:

`WebSocket connection closed. Code: 1015 Reason:`

Could you please help me understand why this is happening?

Thank you again for creating this project. It has been very helpful for my research. <(_ _)>

**Comment by mpromonet** [comment]
Hi @strong0716 

I guess you just need to add 's' to port in order to ask civetweb to listen for https. Something like -P 10060s.

Best Regards 
Michel

**Comment by strong0716** [comment]
Wow! It works perfectly! I used this command:

`rtsp2ws.exe -P 10060s -N 2 -c "keycert.pem" -C config2.json`

Thank you so much for your help. It solved my previous issue completely.

I'd like to bring up another matter I encountered:

When streaming media to the browser, due to security permissions, the video tag must initially be muted. However, when I subsequently unmuted it, I noticed that the video and audio became out of sync.

To address this, I modified the audioprocessor.js file by adding a reset() method to clear the audioBufferQueue. This modification ensures that the audio and video synchronize at the moment when the video transitions from muted to unmuted.

`I've attached the modified source code for your reference. I hope this information might be useful for future improvements or for other users facing similar issues.`

Once again, I want to express my deep appreciation for your project and your prompt assistance. Your work has been invaluable for my research.


[rtsp2ws.zip](https://github.com/user-attachments/files/16385424/rtsp2ws.zip)

**Comment by strong0716** [comment]
Excuse me, I've encountered a new issue while using rtsp2ws and would appreciate your insight.

Issue Description:
I've observed that rtsp2ws seems to only serve one user at a time. Here's what I've noticed:

1. When the first user opens the browser, they can successfully connect to the WebSocket server (wss) and receive media data.
2. When a second user attempts to connect, they can establish a connection to the WebSocket server (wss) but don't receive any media stream data.
3. If the first user closes their browser, the second user then starts receiving media data and can preview the video.

My question is: Is this the intended behavior of rtsp2ws, where it only serves one user at a time? Or could this be due to an error in my setup or usage of the tool?

I would greatly appreciate any clarification or guidance on this matter. Thank you in advance for your help.

**Comment by strong0716** [comment]
Great news! I've found the solution to the issue I previously reported.

The problem was related to the "-N" parameter in rtsp2ws, which represents the maximum number of WebSocket clients allowed. It seems that each connection creates its own thread, which was causing the behavior I observed.

I resolved the issue by setting the "-N" parameter to 100, which now allows multiple users to connect simultaneously.

Thank you for your patience and support. I hope this information might be helpful for other users who encounter similar issues.

**Comment by mpromonet** [comment]
> Wow! It works perfectly! I used this command:
> 
> `rtsp2ws.exe -P 10060s -N 2 -c "keycert.pem" -C config2.json`
> 
> Thank you so much for your help. It solved my previous issue completely.
> 
> I'd like to bring up another matter I encountered:
> 
> When streaming media to the browser, due to security permissions, the video tag must initially be muted. However, when I subsequently unmuted it, I noticed that the video and audio became out of sync.
> 
> To address this, I modified the audioprocessor.js file by adding a reset() method to clear the audioBufferQueue. This modification ensures that the audio and video synchronize at the moment when the video transitions from muted to unmuted.
> 
> `I've attached the modified source code for your reference. I hope this information might be useful for future improvements or for other users facing similar issues.`
> 
> Once again, I want to express my deep appreciation for your project and your prompt assistance. Your work has been invaluable for my research.
> 
> 
> [rtsp2ws.zip](https://github.com/user-attachments/files/16385424/rtsp2ws.zip)
> 
> 

Hi @strong0716 

It is better to submit a pull request.

Best Regards 
Michel
